---
apiVersion: test.openstack.org/v1beta1
kind: AnsibleTest
metadata:
  name: performance-tests
  namespace: openstack
spec:
  extraMounts:
    - name: some-configmap
      subPath: this.conf
      mountPath: /var/conf
  debug: true
  storageClass: local-storage
  workloadSSHKeySecretName: open-ssh-keys
  ansiblePlaybookPath: playbooks/my_playbook.yaml
  ansibleGitRepo: https://github.com/myansible/project
  # containerImage:
  ansibleInventory: |
    localhost ansible_connection=local ansible_python_interpreter=python3
  ansibleVarFiles: |
    ---
    # Use exist cloud resources
    somevar: somevalue

  # Privileged
  # ----------
  #
  # Use with caution! This parameter specifies whether test-operator should spawn test
  # pods with allowedPrivilegedEscalation: true and the default capabilities on
  # top of capabilities that are usually needed by the test pods (NET_ADMIN, NET_RAW).
  # This parameter is deemed insecure but it is needed for certain test-operator
  # functionalities to work properly (e.g.: extraRPMs in Tempest CR, or a certain set
  # of tobiko tests).
  #
  # privileged: false
  #
  # extraMounts:
  #   - extraVol:
  #     - propagation:
  #         - AnsibleTest
  #       extraVolType: ConfigMap
  #       volumes:
  #         - name: configmap-volume
  #           configMap:
  #             name: configmap-name
  #       mounts:
  #         - name: configmap-volume
  #           mountPath: "/etc/config"

  # resources:
  #   limits:
  #     cpu: 4000m
  #     memory: 4Gi
  #   requests:
  #     cpu: 2000m
  #     memory: 2Gi
  workflow:
    - stepName: best-step
      ansibleExtraVars: ' -e manual_run=false '
    - stepName: last-step
      ansibleExtraVars: ' -e manual_run=false '
